name: CI

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    execute-notebook:
        runs-on: ubuntu-latest
        strategy:
            matrix:
              notebook: [sqlite-data-analasis.ipynb]

        steps:
          - name: Checkout repository
            uses: actions/checkout@v4

          - name: Set up Python
            uses: actions/setup-python@v5
            with:
              python-version: 3.x

          - uses: actions/cache@v4
            with:
              path: ~/.cache/pip
              key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
              restore-keys: |
                ${{ runner.os }}-pip-

          - name: Install dependencies
            run: |
              python -m pip install --upgrade pip
              pip install -r ci-requirements.txt
              pip install -r requirements.txt

          - name: Execute notebook
            run: |
              chmod +x ./run-notebook.sh
              ./run-notebook.sh ${{ matrix.notebook }}
              jupyter nbconvert --to notebook \
            working-directory: ${{ github.workspace }}/notebooks
